runtime: nodejs18

service: default

handlers:
  -url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
MONGO_URI: "mongodb+srv://smileline:smileline123@cluster0.wluvozo.mongodb.net/drDB"